import User from "../models/userModel.js";

const getUsers = async (req, res) => {
  try {
    const users = await User.find();
    const usersCount = await User.countDocuments();
    res.set("Content-Range", `users 0-${users.length}/${usersCount}`);
    return res.status(200).json(users);
  } catch (err) {
    console.error("Internal server error ðŸ”´", err);
    res.status(500).json({ error: `${err.message} ðŸ”´` });
  }
};

// const getAllUsers = async (req, res) => {
//   try {
//     const users = await User.find();
//     return res.status(200).json(users);
//   } catch (error) {
//     res.status(404).json({ message: error.message });
//   }
// };

const getUserById = async (req, res) => {
  const { userId } = req.params;
  try {
    const userById = await User.findById(userId);
    if (!userById) {
      return res.status(404).json({ message: "User not found" });
    }
    return res.status(200).json(userById);
  } catch (error) {
    res.status(404).json({ message: error.message });
  }
};

const getUserByToken = async (req, res) => {
  const { token } = req.body;
  try {
    const userByToken = await User.findOne({ token }).select(
      "-password -isAdmin"
    );
    if (!userByToken) {
      return res.status(400).json({ error: "No user found" });
    }
    return res.status(200).json(userByToken);
  } catch (err) {
    console.error("Internal server error ðŸ”´", err);
    res.status(500).json({ error: `${err.message} ðŸ”´` });
  }
};

export { getUsers, getUserById, getUserByToken };
